# Generated by Django 2.2.5 on 2019-10-02 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('instance', models.CharField(default='instance', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('last_welcome_message_id', models.IntegerField(blank=True, null=True)),
                ('log_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='letsMeetBot.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_bot', models.BooleanField(default=False)),
                ('full_name', models.CharField(blank=True, max_length=510, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('message_count', models.IntegerField(default=0)),
                ('warns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.CharField(blank=True, max_length=4096, null=True)),
                ('pinned_message', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('from_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='letsMeetBot.Chat')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='letsMeetBot.User')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_count', models.IntegerField(blank=True, null=True)),
                ('new_members_count', models.IntegerField(default=0)),
                ('messages_count', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letsMeetBot.Chat')),
            ],
        ),
    ]
