# Generated by Django 2.2.5 on 2019-10-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0003_auto_20191005_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='automatic_pin_character',
        ),
        migrations.AddField(
            model_name='chat',
            name='automatic_pin_sequence',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
