# Generated by Django 2.2.5 on 2019-10-06 09:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0004_auto_20191005_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='Europe/Rome'),
        ),
    ]
