# Generated by Django 2.2.5 on 2019-10-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0006_auto_20191007_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('from_message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('proposal_id', models.IntegerField()),
                ('likes', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='letsMeetBot.Chat')),
            ],
        ),
    ]
