# Generated by Django 2.2.5 on 2019-10-08 18:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0007_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='likes',
        ),
        migrations.AddField(
            model_name='proposal',
            name='proposed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='letsMeetBot.User'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='voted_by_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
    ]
