# Generated by Django 2.2.5 on 2019-10-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0008_auto_20191008_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='from_message_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
