# Generated by Django 2.2.5 on 2019-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0009_auto_20191008_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='proposal_message',
            field=models.CharField(default='do you like the proposal?', max_length=1024),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='can_share_to_channel',
            field=models.BooleanField(default=True),
        ),
    ]
