# Generated by Django 2.2.5 on 2019-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0010_auto_20191008_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='proposal_to_channel_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
