# Generated by Django 2.2.5 on 2019-10-08 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0011_chat_proposal_to_channel_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='voted_by_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
