# Generated by Django 2.2.5 on 2019-10-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0012_auto_20191008_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='shared_to_channel',
            field=models.BooleanField(default=False),
        ),
    ]
