# Generated by Django 2.2.5 on 2019-10-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0013_proposal_shared_to_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatuser',
            name='can_share_to_channel',
        ),
        migrations.AddField(
            model_name='chatuser',
            name='instant_share_to_channel',
            field=models.BooleanField(default=False),
        ),
    ]
