# Generated by Django 2.2.5 on 2019-10-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letsMeetBot', '0014_auto_20191008_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='proposal_message',
            field=models.TextField(default='do you like the proposal?', max_length=1024),
        ),
    ]
